export * from "./getMangaController";
export * from "./getPopularMangasController";
export * from "./getLatestUpdatedMangasController";
export * from "./getChaptersController";
export * from "./getChapterNamesController";
export * from "./getSingleChapterController";
export * from "./searchMangasController";
export * from "./getGenreNamesController";
export * from "./getMangasByGenreController";
